### ISSUE TITLE
Add entrypoint to Dockerfile[Feature Request]

### ISSUE THREAD

**Issue by mredenti** [eflows4hpc/image_creation#6]
https://github.com/eflows4hpc/image_creation/blob/b058786e24536d2e00e12dc3d4af293e53a6162c/files/Dockerfile.spack#L1-L27

With the current definition of the Dockerfile the spack environment is not activated by default when spinning  a Docker/Singularity container, a user needs to execute 
`source /etc/profile.d/[z10_spack_environment.sh` within the container. 

I was wondering whether there were any particular reasons for this or if instead this could be a nice feature to have. In other words, is this step of activating the environment something an eFLOWS User should know or is it something we can automate and hide from him?

For example, an entrypoint could be added to the definition of the Dockerfile like so 

`ENTRYPOINT ["source /etc/profile.d/z10_spack_environment.sh"]`

Now, every time the a container is created the environment is sourced upon entry.

**Comment by jorgee** [comment]
We have added an entrypoint, I think this feature is already in the main branch
